title: Bryan Phang Yik Loong
logo: /assets/img/profile-picture.png
description: "Personal Porfolio | Passionate about Web Development & Security"
contact:
  email: "bryanphangyl8135@gmail.com"
  github: "https://github.com/bryanpyl"
  linkedin: "https://www.linkedin.com/in/bryan-phang-yik-loong-7690b8212"
theme: jekyll-theme-minimal