title: Bryan Phang Yik Loong
logo: /assets/img/profile-picture.png
description: "Email: bryanphangyl8135@gmail.com | GitHub: [bryanpyl](https://github.com/bryanpyl) | LinkedIn: [bryan-phang-yik-loong](https://www.linkedin.com/in/bryan-phang-yik-loong-7690b8212)"
#show_downloads: true
theme: jekyll-theme-minimal
